use std::env;
use std::fs;
use std::io::Write;
use std::net::Ipv4Addr;
use std::process::Command;

use super::ruleset::RuleSet;
use rula::parser::ast::RuleSetExpr;

pub fn generate_ruleset(ruleset: &RuleSetExpr) {
    // generate ruleset from rule_expr
    let ruleset_name = &*ruleset.name.name;
    // let ruleset = RuleSet::new(
    //     ruleset_name,
    // );
}

// Helper function to generate
pub fn generate_file(program: RuleSet, file_name: &str) {
    let mut file_path = env::current_dir().unwrap();
    file_path.push("tests");
    file_path.push("generated");
    file_path.push(file_name);
    let mut file = fs::File::create(file_path.clone()).unwrap();
    // writeln!(file, "// This is autogenerated Rust program \n{}", program).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_make_json() {
        // let ruleset = generate_ruleset();
    }
}
