[package]
name = "rula-parser"
version = "0.1.0"
edition = "2021"
description = "A parser for RuLa programming language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
once_cell = "1.15.0"