on: [push]

name: Build and unit testing

jobs:
  build_and_test:
    name: Unit testing
    strategy:
      matrix:
        version: ['macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: cargo test